//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for common.i18n.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="common.i18n">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fail.to.cleanup.resource"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "common.i18n", namespace = "http://footprint.dev.java.net/generated/i18n")
@XmlEnum
public enum CommonI18N {

    @XmlEnumValue("fail.to.cleanup.resource")
    FAIL_TO_CLEANUP_RESOURCE("fail.to.cleanup.resource");
    private final String value;

    CommonI18N(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CommonI18N fromValue(String v) {
        for (CommonI18N c : CommonI18N.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
