//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ConfigEmail complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigEmail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="msg.body" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="msg.from" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="msg.subject" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="smtp.auth" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="smtp.content.type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="smtp.host" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="smtp.password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="smtp.user" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="smtp.star.ttls.enable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="smtp.transfer.protocol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="socks.proxy.port" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="socks.proxy.host" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="post.processing.type" type="{http://footprint.dev.java.net/generated/config}post.process.mode" />
 *       &lt;attribute name="post.processing.rename.sufix" type="{http://www.w3.org/2001/XMLSchema}string" default=".sent" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigEmail", propOrder = { "msgBody" })
public class ConfigEmail implements Serializable {

    private final static long serialVersionUID = -6908316602239211070L;
    @XmlElement(name = "msg.body")
    protected String msgBody;
    @XmlAttribute(name = "msg.from")
    protected String msgFrom;
    @XmlAttribute(name = "msg.subject")
    protected String msgSubject;
    @XmlAttribute(name = "smtp.auth")
    protected Boolean smtpAuth;
    @XmlAttribute(name = "smtp.content.type")
    protected String smtpContentType;
    @XmlAttribute(name = "smtp.host")
    protected String smtpHost;
    @XmlAttribute(name = "smtp.password")
    protected String smtpPassword;
    @XmlAttribute(name = "smtp.user")
    protected String smtpUser;
    @XmlAttribute(name = "smtp.star.ttls.enable")
    protected Boolean smtpStarTtlsEnable;
    @XmlAttribute(name = "smtp.transfer.protocol")
    protected String smtpTransferProtocol;
    @XmlAttribute(name = "socks.proxy.port")
    protected String socksProxyPort;
    @XmlAttribute(name = "socks.proxy.host")
    protected String socksProxyHost;
    @XmlAttribute(name = "post.processing.type")
    protected PostProcessMode postProcessingType;
    @XmlAttribute(name = "post.processing.rename.sufix")
    protected String postProcessingRenameSufix;

    /**
     * Gets the value of the msgBody property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMsgBody() {
        return msgBody;
    }

    /**
     * Sets the value of the msgBody property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMsgBody(String value) {
        this.msgBody = value;
    }

    /**
     * Gets the value of the msgFrom property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMsgFrom() {
        return msgFrom;
    }

    /**
     * Sets the value of the msgFrom property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMsgFrom(String value) {
        this.msgFrom = value;
    }

    /**
     * Gets the value of the msgSubject property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMsgSubject() {
        return msgSubject;
    }

    /**
     * Sets the value of the msgSubject property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMsgSubject(String value) {
        this.msgSubject = value;
    }

    /**
     * Gets the value of the smtpAuth property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isSmtpAuth() {
        return smtpAuth;
    }

    /**
     * Sets the value of the smtpAuth property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setSmtpAuth(Boolean value) {
        this.smtpAuth = value;
    }

    /**
     * Gets the value of the smtpContentType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSmtpContentType() {
        return smtpContentType;
    }

    /**
     * Sets the value of the smtpContentType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSmtpContentType(String value) {
        this.smtpContentType = value;
    }

    /**
     * Gets the value of the smtpHost property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSmtpHost() {
        return smtpHost;
    }

    /**
     * Sets the value of the smtpHost property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSmtpHost(String value) {
        this.smtpHost = value;
    }

    /**
     * Gets the value of the smtpPassword property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSmtpPassword() {
        return smtpPassword;
    }

    /**
     * Sets the value of the smtpPassword property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSmtpPassword(String value) {
        this.smtpPassword = value;
    }

    /**
     * Gets the value of the smtpUser property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSmtpUser() {
        return smtpUser;
    }

    /**
     * Sets the value of the smtpUser property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSmtpUser(String value) {
        this.smtpUser = value;
    }

    /**
     * Gets the value of the smtpStarTtlsEnable property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isSmtpStarTtlsEnable() {
        return smtpStarTtlsEnable;
    }

    /**
     * Sets the value of the smtpStarTtlsEnable property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setSmtpStarTtlsEnable(Boolean value) {
        this.smtpStarTtlsEnable = value;
    }

    /**
     * Gets the value of the smtpTransferProtocol property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSmtpTransferProtocol() {
        return smtpTransferProtocol;
    }

    /**
     * Sets the value of the smtpTransferProtocol property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSmtpTransferProtocol(String value) {
        this.smtpTransferProtocol = value;
    }

    /**
     * Gets the value of the socksProxyPort property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSocksProxyPort() {
        if (socksProxyPort == null) {
            return "";
        } else {
            return socksProxyPort;
        }
    }

    /**
     * Sets the value of the socksProxyPort property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSocksProxyPort(String value) {
        this.socksProxyPort = value;
    }

    /**
     * Gets the value of the socksProxyHost property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSocksProxyHost() {
        if (socksProxyHost == null) {
            return "";
        } else {
            return socksProxyHost;
        }
    }

    /**
     * Sets the value of the socksProxyHost property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSocksProxyHost(String value) {
        this.socksProxyHost = value;
    }

    /**
     * Gets the value of the postProcessingType property.
     * 
     * @return possible object is {@link PostProcessMode }
     * 
     */
    public PostProcessMode getPostProcessingType() {
        return postProcessingType;
    }

    /**
     * Sets the value of the postProcessingType property.
     * 
     * @param value
     *            allowed object is {@link PostProcessMode }
     * 
     */
    public void setPostProcessingType(PostProcessMode value) {
        this.postProcessingType = value;
    }

    /**
     * Gets the value of the postProcessingRenameSufix property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPostProcessingRenameSufix() {
        if (postProcessingRenameSufix == null) {
            return ".sent";
        } else {
            return postProcessingRenameSufix;
        }
    }

    /**
     * Sets the value of the postProcessingRenameSufix property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPostProcessingRenameSufix(String value) {
        this.postProcessingRenameSufix = value;
    }

}
