//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ConfigSecurity complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigSecurity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="signature.stamp" type="{http://footprint.dev.java.net/generated/config}SignatureStamp"/>
 *       &lt;/sequence>
 *       &lt;attribute name="keystore.filename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keystore.type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keystore.password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keystore.pk.alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keystore.pk.password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keystore.pk.provider" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="signature.crypto.name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="signature.contact.mail" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="signature.location" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="signature.reason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigSecurity", propOrder = { "signatureStamp" })
public class ConfigSecurity implements Serializable {

    private final static long serialVersionUID = -6908316602239211070L;
    @XmlElement(name = "signature.stamp")
    protected SignatureStamp signatureStamp;
    @XmlAttribute(name = "keystore.filename")
    protected String keystoreFilename;
    @XmlAttribute(name = "keystore.type")
    protected String keystoreType;
    @XmlAttribute(name = "keystore.password")
    protected String keystorePassword;
    @XmlAttribute(name = "keystore.pk.alias")
    protected String keystorePkAlias;
    @XmlAttribute(name = "keystore.pk.password")
    protected String keystorePkPassword;
    @XmlAttribute(name = "keystore.pk.provider")
    protected String keystorePkProvider;
    @XmlAttribute(name = "signature.crypto.name")
    protected String signatureCryptoName;
    @XmlAttribute(name = "signature.contact.mail")
    protected String signatureContactMail;
    @XmlAttribute(name = "signature.location")
    protected String signatureLocation;
    @XmlAttribute(name = "signature.reason")
    protected String signatureReason;

    /**
     * Gets the value of the signatureStamp property.
     * 
     * @return possible object is {@link SignatureStamp }
     * 
     */
    public SignatureStamp getSignatureStamp() {
        return signatureStamp;
    }

    /**
     * Sets the value of the signatureStamp property.
     * 
     * @param value
     *            allowed object is {@link SignatureStamp }
     * 
     */
    public void setSignatureStamp(SignatureStamp value) {
        this.signatureStamp = value;
    }

    /**
     * Gets the value of the keystoreFilename property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKeystoreFilename() {
        return keystoreFilename;
    }

    /**
     * Sets the value of the keystoreFilename property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKeystoreFilename(String value) {
        this.keystoreFilename = value;
    }

    /**
     * Gets the value of the keystoreType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKeystoreType() {
        return keystoreType;
    }

    /**
     * Sets the value of the keystoreType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKeystoreType(String value) {
        this.keystoreType = value;
    }

    /**
     * Gets the value of the keystorePassword property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKeystorePassword() {
        return keystorePassword;
    }

    /**
     * Sets the value of the keystorePassword property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKeystorePassword(String value) {
        this.keystorePassword = value;
    }

    /**
     * Gets the value of the keystorePkAlias property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKeystorePkAlias() {
        return keystorePkAlias;
    }

    /**
     * Sets the value of the keystorePkAlias property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKeystorePkAlias(String value) {
        this.keystorePkAlias = value;
    }

    /**
     * Gets the value of the keystorePkPassword property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKeystorePkPassword() {
        return keystorePkPassword;
    }

    /**
     * Sets the value of the keystorePkPassword property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKeystorePkPassword(String value) {
        this.keystorePkPassword = value;
    }

    /**
     * Gets the value of the keystorePkProvider property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKeystorePkProvider() {
        return keystorePkProvider;
    }

    /**
     * Sets the value of the keystorePkProvider property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKeystorePkProvider(String value) {
        this.keystorePkProvider = value;
    }

    /**
     * Gets the value of the signatureCryptoName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSignatureCryptoName() {
        return signatureCryptoName;
    }

    /**
     * Sets the value of the signatureCryptoName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSignatureCryptoName(String value) {
        this.signatureCryptoName = value;
    }

    /**
     * Gets the value of the signatureContactMail property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSignatureContactMail() {
        return signatureContactMail;
    }

    /**
     * Sets the value of the signatureContactMail property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSignatureContactMail(String value) {
        this.signatureContactMail = value;
    }

    /**
     * Gets the value of the signatureLocation property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSignatureLocation() {
        return signatureLocation;
    }

    /**
     * Sets the value of the signatureLocation property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSignatureLocation(String value) {
        this.signatureLocation = value;
    }

    /**
     * Gets the value of the signatureReason property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSignatureReason() {
        return signatureReason;
    }

    /**
     * Sets the value of the signatureReason property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSignatureReason(String value) {
        this.signatureReason = value;
    }

}
