//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The information about the JDBC connection used to retrieve the data to fill
 * the PDF forms.
 * 
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigJdbc", propOrder = { "driverProperties" })
public class ConfigJdbc implements Serializable {

    private final static long serialVersionUID = -6908316602239211070L;
    @XmlElement(name = "driver.properties")
    protected DriverProperties driverProperties;
    @XmlAttribute(name = "jdbc.driver.classname")
    protected String jdbcDriverClassname;
    @XmlAttribute(name = "jdbc.connection.url")
    protected String jdbcConnectionUrl;
    @XmlAttribute(name = "jdbc.query")
    protected String jdbcQuery;
    @XmlAttribute(name = "email.column.name")
    protected String emailColumnName;

    /**
     * Gets the value of the driverProperties property.
     * 
     * @return possible object is {@link DriverProperties }
     * 
     */
    public DriverProperties getDriverProperties() {
        return driverProperties;
    }

    /**
     * Sets the value of the driverProperties property.
     * 
     * @param value
     *            allowed object is {@link DriverProperties }
     * 
     */
    public void setDriverProperties(DriverProperties value) {
        this.driverProperties = value;
    }

    /**
     * Gets the value of the jdbcDriverClassname property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getJdbcDriverClassname() {
        return jdbcDriverClassname;
    }

    /**
     * Sets the value of the jdbcDriverClassname property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setJdbcDriverClassname(String value) {
        this.jdbcDriverClassname = value;
    }

    /**
     * Gets the value of the jdbcConnectionUrl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getJdbcConnectionUrl() {
        return jdbcConnectionUrl;
    }

    /**
     * Sets the value of the jdbcConnectionUrl property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setJdbcConnectionUrl(String value) {
        this.jdbcConnectionUrl = value;
    }

    /**
     * Gets the value of the jdbcQuery property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getJdbcQuery() {
        return jdbcQuery;
    }

    /**
     * Sets the value of the jdbcQuery property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setJdbcQuery(String value) {
        this.jdbcQuery = value;
    }

    /**
     * Gets the value of the emailColumnName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEmailColumnName() {
        return emailColumnName;
    }

    /**
     * Sets the value of the emailColumnName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEmailColumnName(String value) {
        this.emailColumnName = value;
    }

}
