//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for config.unmarshal.i18n.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="config.unmarshal.i18n">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="config.validating"/>
 *     &lt;enumeration value="config.template.file.not.found"/>
 *     &lt;enumeration value="config.email.mallformed"/>
 *     &lt;enumeration value="config.errors.header"/>
 *     &lt;enumeration value="config.keystore.file.not.found"/>
 *     &lt;enumeration value="config.keystore.alias.unknown"/>
 *     &lt;enumeration value="config.keystore.stamp.not.found"/>
 *     &lt;enumeration value="config.keystore.generic.problem"/>
 *     &lt;enumeration value="config.keystore.unloadable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "config.unmarshal.i18n", namespace = "http://footprint.dev.java.net/generated/i18n")
@XmlEnum
public enum ConfigUnmarshalI18N {

    @XmlEnumValue("config.validating")
    CONFIG_VALIDATING("config.validating"), @XmlEnumValue("config.template.file.not.found")
    CONFIG_TEMPLATE_FILE_NOT_FOUND("config.template.file.not.found"), @XmlEnumValue("config.email.mallformed")
    CONFIG_EMAIL_MALLFORMED("config.email.mallformed"), @XmlEnumValue("config.errors.header")
    CONFIG_ERRORS_HEADER("config.errors.header"), @XmlEnumValue("config.keystore.file.not.found")
    CONFIG_KEYSTORE_FILE_NOT_FOUND("config.keystore.file.not.found"), @XmlEnumValue("config.keystore.alias.unknown")
    CONFIG_KEYSTORE_ALIAS_UNKNOWN("config.keystore.alias.unknown"), @XmlEnumValue("config.keystore.stamp.not.found")
    CONFIG_KEYSTORE_STAMP_NOT_FOUND("config.keystore.stamp.not.found"), @XmlEnumValue("config.keystore.generic.problem")
    CONFIG_KEYSTORE_GENERIC_PROBLEM("config.keystore.generic.problem"), @XmlEnumValue("config.keystore.unloadable")
    CONFIG_KEYSTORE_UNLOADABLE("config.keystore.unloadable");
    private final String value;

    ConfigUnmarshalI18N(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConfigUnmarshalI18N fromValue(String v) {
        for (ConfigUnmarshalI18N c : ConfigUnmarshalI18N.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
