//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * PDF template is a PDF document with <em>acro forms</em>. <br/>
 * The field of this element refers to a file, like the name and the path of the
 * file as well as the charset and the sufix/prefix of the file. More info on
 * how to include forms in PDF documents: <a
 * href='http://plpdf.com/dokumentumok/plpdf_oo_form.pdf'>
 * http://plpdf.com/dokumentumok/plpdf_oo_form.pdf</a> or <a href=
 * 'http://www.acrobatusers.com/articles/2006/07/getting_started_forms/index.php'
 * > http://www.acrobatusers.com/articles/2006/07/getting_started_forms/index.
 * php</a>
 * 
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigPdfTemplate")
public class ConfigPdfTemplate implements Serializable {

    private final static long serialVersionUID = -6908316602239211070L;
    @XmlAttribute(name = "pdf.template.filename")
    protected String pdfTemplateFilename;
    @XmlAttribute(name = "pdf.template.charset")
    protected String pdfTemplateCharset;
    @XmlAttribute(name = "pdf.generated.path")
    protected String pdfGeneratedPath;
    @XmlAttribute(name = "pdf.generated.prefix")
    protected String pdfGeneratedPrefix;
    @XmlAttribute(name = "pdf.generated.extension")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String pdfGeneratedExtension;
    @XmlAttribute(name = "pdf.generated.charset")
    protected String pdfGeneratedCharset;
    @XmlAttribute(name = "replaceable")
    protected Boolean replaceable;

    /**
     * Gets the value of the pdfTemplateFilename property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPdfTemplateFilename() {
        return pdfTemplateFilename;
    }

    /**
     * Sets the value of the pdfTemplateFilename property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPdfTemplateFilename(String value) {
        this.pdfTemplateFilename = value;
    }

    /**
     * Gets the value of the pdfTemplateCharset property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPdfTemplateCharset() {
        return pdfTemplateCharset;
    }

    /**
     * Sets the value of the pdfTemplateCharset property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPdfTemplateCharset(String value) {
        this.pdfTemplateCharset = value;
    }

    /**
     * Gets the value of the pdfGeneratedPath property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPdfGeneratedPath() {
        if (pdfGeneratedPath == null) {
            return "./generated";
        } else {
            return pdfGeneratedPath;
        }
    }

    /**
     * Sets the value of the pdfGeneratedPath property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPdfGeneratedPath(String value) {
        this.pdfGeneratedPath = value;
    }

    /**
     * Gets the value of the pdfGeneratedPrefix property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPdfGeneratedPrefix() {
        if (pdfGeneratedPrefix == null) {
            return "generated";
        } else {
            return pdfGeneratedPrefix;
        }
    }

    /**
     * Sets the value of the pdfGeneratedPrefix property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPdfGeneratedPrefix(String value) {
        this.pdfGeneratedPrefix = value;
    }

    /**
     * Gets the value of the pdfGeneratedExtension property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPdfGeneratedExtension() {
        if (pdfGeneratedExtension == null) {
            return ".pdf";
        } else {
            return pdfGeneratedExtension;
        }
    }

    /**
     * Sets the value of the pdfGeneratedExtension property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPdfGeneratedExtension(String value) {
        this.pdfGeneratedExtension = value;
    }

    /**
     * Gets the value of the pdfGeneratedCharset property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPdfGeneratedCharset() {
        return pdfGeneratedCharset;
    }

    /**
     * Sets the value of the pdfGeneratedCharset property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPdfGeneratedCharset(String value) {
        this.pdfGeneratedCharset = value;
    }

    /**
     * Gets the value of the replaceable property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public boolean isReplaceable() {
        if (replaceable == null) {
            return true;
        } else {
            return replaceable;
        }
    }

    /**
     * Sets the value of the replaceable property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setReplaceable(Boolean value) {
        this.replaceable = value;
    }

}
