//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for exporter.i18n.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="exporter.i18n">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="folder.created"/>
 *     &lt;enumeration value="path.failure"/>
 *     &lt;enumeration value="pdf.pdf.overwrite"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "exporter.i18n", namespace = "http://footprint.dev.java.net/generated/i18n")
@XmlEnum
public enum ExporterI18N {

    @XmlEnumValue("folder.created")
    FOLDER_CREATED("folder.created"), @XmlEnumValue("path.failure")
    PATH_FAILURE("path.failure"), @XmlEnumValue("pdf.pdf.overwrite")
    PDF_PDF_OVERWRITE("pdf.pdf.overwrite");
    private final String value;

    ExporterI18N(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExporterI18N fromValue(String v) {
        for (ExporterI18N c : ExporterI18N.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
