//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * The top level element is a sequence of all other, plus some versioning
 * attributes.
 * 
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "footprint.config", propOrder = { "template", "security", "database", "pdf2Jdbc", "fonts", "email" })
public class FootprintConfig implements Serializable {

    private final static long serialVersionUID = -6908316602239211070L;
    @XmlElement(required = true)
    protected ConfigPdfTemplate template;
    @XmlElement(required = true)
    protected ConfigSecurity security;
    @XmlElement(required = true)
    protected ConfigJdbc database;
    @XmlElement(name = "pdf2jdbc", required = true)
    protected ConfigMapping pdf2Jdbc;
    @XmlElement(required = true, nillable = true)
    protected TrueTypeFileMapping fonts;
    @XmlElement(required = true)
    protected ConfigEmail email;
    @XmlAttribute(name = "title")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String title;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "date")
    protected String date;
    @XmlAttribute(name = "idiom")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String idiom;

    /**
     * Gets the value of the template property.
     * 
     * @return possible object is {@link ConfigPdfTemplate }
     * 
     */
    public ConfigPdfTemplate getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *            allowed object is {@link ConfigPdfTemplate }
     * 
     */
    public void setTemplate(ConfigPdfTemplate value) {
        this.template = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return possible object is {@link ConfigSecurity }
     * 
     */
    public ConfigSecurity getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *            allowed object is {@link ConfigSecurity }
     * 
     */
    public void setSecurity(ConfigSecurity value) {
        this.security = value;
    }

    /**
     * Gets the value of the database property.
     * 
     * @return possible object is {@link ConfigJdbc }
     * 
     */
    public ConfigJdbc getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *            allowed object is {@link ConfigJdbc }
     * 
     */
    public void setDatabase(ConfigJdbc value) {
        this.database = value;
    }

    /**
     * Gets the value of the pdf2Jdbc property.
     * 
     * @return possible object is {@link ConfigMapping }
     * 
     */
    public ConfigMapping getPdf2Jdbc() {
        return pdf2Jdbc;
    }

    /**
     * Sets the value of the pdf2Jdbc property.
     * 
     * @param value
     *            allowed object is {@link ConfigMapping }
     * 
     */
    public void setPdf2Jdbc(ConfigMapping value) {
        this.pdf2Jdbc = value;
    }

    /**
     * Gets the value of the fonts property.
     * 
     * @return possible object is {@link TrueTypeFileMapping }
     * 
     */
    public TrueTypeFileMapping getFonts() {
        return fonts;
    }

    /**
     * Sets the value of the fonts property.
     * 
     * @param value
     *            allowed object is {@link TrueTypeFileMapping }
     * 
     */
    public void setFonts(TrueTypeFileMapping value) {
        this.fonts = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return possible object is {@link ConfigEmail }
     * 
     */
    public ConfigEmail getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *            allowed object is {@link ConfigEmail }
     * 
     */
    public void setEmail(ConfigEmail value) {
        this.email = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the idiom property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdiom() {
        return idiom;
    }

    /**
     * Sets the value of the idiom property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdiom(String value) {
        this.idiom = value;
    }

}
