//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for mailer.i18n.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="mailer.i18n">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="mailer.sent.ok"/>
 *     &lt;enumeration value="mailer.sent.not.ok"/>
 *     &lt;enumeration value="mailer.sent.rename.failure"/>
 *     &lt;enumeration value="mailer.sent.move.failure"/>
 *     &lt;enumeration value="mailer.empty.folder"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "mailer.i18n", namespace = "http://footprint.dev.java.net/generated/i18n")
@XmlEnum
public enum MailerI18N {

    @XmlEnumValue("mailer.sent.ok")
    MAILER_SENT_OK("mailer.sent.ok"), @XmlEnumValue("mailer.sent.not.ok")
    MAILER_SENT_NOT_OK("mailer.sent.not.ok"), @XmlEnumValue("mailer.sent.rename.failure")
    MAILER_SENT_RENAME_FAILURE("mailer.sent.rename.failure"), @XmlEnumValue("mailer.sent.move.failure")
    MAILER_SENT_MOVE_FAILURE("mailer.sent.move.failure"), @XmlEnumValue("mailer.empty.folder")
    MAILER_EMPTY_FOLDER("mailer.empty.folder");
    private final String value;

    MailerI18N(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MailerI18N fromValue(String v) {
        for (MailerI18N c : MailerI18N.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
