//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.cejug.footprint.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Configuration_QNAME = new QName("http://footprint.dev.java.net/generated/config", "configuration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.cejug.footprint.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FootprintConfig }
     * 
     */
    public FootprintConfig createFootprintConfig() {
        return new FootprintConfig();
    }

    /**
     * Create an instance of {@link SignatureStamp }
     * 
     */
    public SignatureStamp createSignatureStamp() {
        return new SignatureStamp();
    }

    /**
     * Create an instance of {@link Pdf2JdbcMapping }
     * 
     */
    public Pdf2JdbcMapping createPdf2JdbcMapping() {
        return new Pdf2JdbcMapping();
    }

    /**
     * Create an instance of {@link ConfigEmail }
     * 
     */
    public ConfigEmail createConfigEmail() {
        return new ConfigEmail();
    }

    /**
     * Create an instance of {@link ConfigSecurity }
     * 
     */
    public ConfigSecurity createConfigSecurity() {
        return new ConfigSecurity();
    }

    /**
     * Create an instance of {@link ConfigMapping }
     * 
     */
    public ConfigMapping createConfigMapping() {
        return new ConfigMapping();
    }

    /**
     * Create an instance of {@link DriverProperties }
     * 
     */
    public DriverProperties createDriverProperties() {
        return new DriverProperties();
    }

    /**
     * Create an instance of {@link JdbcDriverProperties }
     * 
     */
    public JdbcDriverProperties createJdbcDriverProperties() {
        return new JdbcDriverProperties();
    }

    /**
     * Create an instance of {@link TrueTypeFileMapping }
     * 
     */
    public TrueTypeFileMapping createTrueTypeFileMapping() {
        return new TrueTypeFileMapping();
    }

    /**
     * Create an instance of {@link ConfigPdfTemplate }
     * 
     */
    public ConfigPdfTemplate createConfigPdfTemplate() {
        return new ConfigPdfTemplate();
    }

    /**
     * Create an instance of {@link FontMapping }
     * 
     */
    public FontMapping createFontMapping() {
        return new FontMapping();
    }

    /**
     * Create an instance of {@link ConfigJdbc }
     * 
     */
    public ConfigJdbc createConfigJdbc() {
        return new ConfigJdbc();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FootprintConfig }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://footprint.dev.java.net/generated/config", name = "configuration")
    public JAXBElement<FootprintConfig> createConfiguration(FootprintConfig value) {
        return new JAXBElement<FootprintConfig>(_Configuration_QNAME, FootprintConfig.class, null, value);
    }

}
