//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://footprint.dev.java.net/generated/config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cejug.footprint.jaxb;

