//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 09:58:49 PM BRT 
//

package org.cejug.footprint.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SignatureStamp complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SignatureStamp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="signature.field.name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="signature.stamp.image.filename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="signature.stamp.x1" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="signature.stamp.y1" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="signature.stamp.x2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="signature.stamp.y2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureStamp")
public class SignatureStamp implements Serializable {

    private final static long serialVersionUID = -6908316602239211070L;
    @XmlAttribute(name = "signature.field.name")
    protected String signatureFieldName;
    @XmlAttribute(name = "signature.stamp.image.filename")
    protected String signatureStampImageFilename;
    @XmlAttribute(name = "signature.stamp.x1")
    protected Integer signatureStampX1;
    @XmlAttribute(name = "signature.stamp.y1")
    protected Integer signatureStampY1;
    @XmlAttribute(name = "signature.stamp.x2")
    protected Integer signatureStampX2;
    @XmlAttribute(name = "signature.stamp.y2")
    protected Integer signatureStampY2;

    /**
     * Gets the value of the signatureFieldName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSignatureFieldName() {
        return signatureFieldName;
    }

    /**
     * Sets the value of the signatureFieldName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSignatureFieldName(String value) {
        this.signatureFieldName = value;
    }

    /**
     * Gets the value of the signatureStampImageFilename property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSignatureStampImageFilename() {
        return signatureStampImageFilename;
    }

    /**
     * Sets the value of the signatureStampImageFilename property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSignatureStampImageFilename(String value) {
        this.signatureStampImageFilename = value;
    }

    /**
     * Gets the value of the signatureStampX1 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getSignatureStampX1() {
        return signatureStampX1;
    }

    /**
     * Sets the value of the signatureStampX1 property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setSignatureStampX1(Integer value) {
        this.signatureStampX1 = value;
    }

    /**
     * Gets the value of the signatureStampY1 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getSignatureStampY1() {
        return signatureStampY1;
    }

    /**
     * Sets the value of the signatureStampY1 property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setSignatureStampY1(Integer value) {
        this.signatureStampY1 = value;
    }

    /**
     * Gets the value of the signatureStampX2 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getSignatureStampX2() {
        return signatureStampX2;
    }

    /**
     * Sets the value of the signatureStampX2 property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setSignatureStampX2(Integer value) {
        this.signatureStampX2 = value;
    }

    /**
     * Gets the value of the signatureStampY2 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getSignatureStampY2() {
        return signatureStampY2;
    }

    /**
     * Sets the value of the signatureStampY2 property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setSignatureStampY2(Integer value) {
        this.signatureStampY2 = value;
    }

}
